### ISSUE TITLE
Potential sharing of kernel memory

### ISSUE THREAD

**Issue by codido** [tock/tock#1141]
When a process issues the allow syscall, the range is checked in order to verify that the memory buffer does not overlap with the grants region.

However, brk can be used to reduce the memory region reserved for the process without invalidating the allowed memory buffer. This can be problematic if a grant is later on allocated in the same region, as it could still be accessed by another driver.

**Comment by alevy** [comment]
I believe this is indeed a bug. @codido discusses a fix where the `Process` would store the "high-water-mark" of all `allow`ed AppSlices for a process, and refuse to change the break below that water mark.

Alternatively, we could explicitly check the accessible process memory on each AppSlice dereference.

The first options seem a better trade-off since most processes will likely allocate appslices in the data region, below the dynamic heap anyway (it's definitely easiest to do this due to the alignment requirements).
