### ISSUE TITLE
Possible bug in TRNG interrupt?

### ISSUE THREAD

**Issue by ppannuto** [tock/tock#1332]
I was futzing with some other stuff and noticed this by happenstance. It's been around [since the beginning](https://github.com/tock/tock/commit/ea34ab5a4aa6fcc4bd6137cd54406e8fa230cd2c?diff=unified#diff-09a7f11fc0b1946fe9a27d66aa3fd64eR42), but I think [this line](https://github.com/tock/tock/blob/master/chips/sam4l/src/trng.rs#L67) should be checking the `isr` rather than the `imr`. In principle, this interrupt should never trigger until the `isr` evaluates to true anyway, but feels like this kind of thing that could be frustrating to track down in the future if we ever did more with the TRNG. Amit, am I missing anything here?

**Comment by alevy** [comment]
This is from early enough that I'm guessing I actually was doing this when we had a queue for interrupts and it was possible for an additional interrupt for the same peripheral to be queued before the first had been handled. In the case of a TRNG that's dangerous since we could end up returning the second "random" value twice.

But this is no longer relevant, so I think we should just remove that check.
