### ISSUE TITLE
Update HIL for analog_comparator

### ISSUE THREAD

**Issue by lgnashold** [tock/tock#1526]
I'm in the process of writing a driver for the nrf52840 implementation of the analog comparator, and it looks like there's some changes that might be needed to the HIL to make it general enough to use effectively with both the sam4l (already existing) and nrf52840 (new) drivers. I'm tagging you two (@bradjc @brghena ) because it looks like you did a lot of the review on the original HIL and sam4l driver. 

The main difference between the two AC's is that the sam4l is actually a set of AC's (up to four) whereas the nrf52840 is just one. However, each AC in the sam4l has two dedicated pins, whereas the AC in the nrf52840 can be configured to use any two pins of eight pins. The nrf52840 can also make comparisons against set voltages (1.2V, 1.8V, 2.4V, and VDD), which the sam4l cannot. Secondarily, the sam4l can use windowed mode, which currently isn't implemented, and they both can use an optional hysteresis, which also isn't implemented. 

Currently, in my opinion, the HIL is too specific to the sam4l implementation. The main problem is that there is no way for the user of the HIL to specify a configuration for the comparator. For the sam4l, this isn't a major issue, because each AC has dedicated pins. However, I think it will be important for the user to be able to choose which pins they want to use for the nrf52840.

To modify the HIL, we could add another parameter to the start_comparing and comparison methods specifying the configuration of the AC. The type of this parameter would be implementation-specific. This configuration would also allow for easier enabling of optional features like hysteresis. A problem with this approach is that it would mean the system call and capsule would need extra parameters to specify these configuration options. This would mean that the capsule might either be not hardware-agnostic or that some parameters needed by the nrf52840 would be unused by the sam4l and vice versa. 

The other approach would be to hardcode the pins used by the nrf52840. This seems like bad practice, but it would mean not having to modify the HIL. Since the AC pins also double as GPIO pins, it would force users to use specific GPIO pins for the AC. 
I had a few other questions about past design decisions. My initial thought was to create add enable methods to the HIL, to specify the configuration, and leave the rest unchanged. However, it looks like an enable method was actually proposed and then removed in the original PR. Do either of you know why this was? Also, it looks like the disable method in the sam4l specific implementation is never called, leaving the comparator always on once it's first used. Do you know the logic behind this as well? 

Thank you for your help! This might be what the new function signatures might look like in the HIL:
```rust
 pub trait AnalogComparator {
    type Config;
    type Channel;
   
    /// Do a single comparison of two inputs, depending on the AC chosen. Output
    /// will be True (1) when one is higher than the other, and False (0)
    /// otherwise.  Specifically, the output is True when Vp > Vn (Vin positive
    /// > Vin negative), and False if Vp < Vn.
    fn comparison(&self, channel: &Self::Channel) -> bool;

    /// Start interrupt-based comparison for the chosen channel (e.g. channel 1
    /// for AC1). This will make it listen and send an interrupt as soon as
    /// Vp > Vn.
    fn start_comparing(&self, channel: &Self::Channel) -> ReturnCode;

    /// Stop interrupt-based comparison for the chosen channel.
    fn stop_comparing(&self, channel: &Self::Channel) -> ReturnCode;
}
```

**Comment by bradjc** [comment]
For the issue of setting which pins are connected to the comparator, I think that is explicitly _not_ included in the HIL, as the user of the AC just wants to be able to use the AC without having to worry about how pins are mapped on a specific board. This is very similar to how setting which I2C pins are used is not in the I2C HIL, since only the board needs to know that, not the IC driver which needs to use I2C.

The board-specific configuration (like mapping pins) can be done by just calling the nRF AC driver directly. If there are generic usage configuration options then those could be exposed in the HIL. For example, the UART HIL has a configure function. I'm not sure if using a fixed voltage would be considered something a user would want to set or something that is fixed based on the hardware design.

Generally HILs in Tock start simple, and evolve as we use them more and more platforms support them. So it is very reasonable that we need to iterate on the AC HIL.

The explicit enable and disable were removed because they added additional confusion for users of the HIL, particularly when the implementation can just internally enable and disable the hardware. (The SAM4L driver may be buggy.)
