### ISSUE TITLE
time hils over specify lifetime on &self parameter in functions

### ISSUE THREAD

**Issue by jettr** [tock/tock#2851]
Taking a look at the `Alarm` hil, it currently specifies `'a` for the `self` parameter on the `fn set_alarm_client(&'a self, client: &'a dyn AlarmClient);` function, but self should use the normal, unspecified, anonymous lifetime for self instead. The client parameter still should have `'a` since that is the reference that `Alarm<'a>` needs to hold on to.

The same thing happens on the `Timer` trait:
 * `fn set_timer_client(&'a self, client: &'a dyn TimerClient);`
 * `fn oneshot(&'a self, interval: Self::Ticks) -> Self::Ticks;`
 * `fn repeating(&'a self, interval: Self::Ticks) -> Self::Ticks;`

The `self` parameter should not require the `'a` lifetime.

Also worth noting that the `Alarm` trait already does not specify a lifetime constraint on `fn set_alarm(&self, reference: Self::Ticks, dt: Self::Ticks);`. So it isn't technically required to engage the alarm or timer.

So the next questions is why and how did we get here, and can we just remove the `'a`?

After tracing the code, it appears that we added `'a` on `self` for these methods because the implementation of `VirtualMuxAlarm` and `VirtualMuxTimer` used linked listed internally. These linked lists require a valid reference for the lifetime of the list, namely `'a`. So I believe the reason `'a` is on the hil is due to leaking implementation details of these commonly used VirtualMux implementations. 

We should stop leaking these implementation details on this hil. How do we fix it?

Once way to fix (i.e. drop the `'a` on the hil interfaces) is to require that after a  `VirtualMuxAlarm` has been created (which takes in a refernce to `MuxAlarm`) we call a new `link(virtual_alarm: &'a VirtualAlarmMux)` on `MuxAlarm` after creating the `VirtualMuxAlarm::new()`. This requires a two step initialization for `VirtualAlarmMux` and could be prone to mistakes, but it alleviates the lifetime issue. Could we perhaps use the `Component` and `finalize` paradigm to ensure that VirtualMuxAlarms are always created correctly, i.e `VirtualAlarmMux::new` then `MuxAlarm::link`?

Also there is a comment on `VirtualSchedulerTimer`:
```
        // However, because of how the MuxAlarm code is written, if the passed
        // alarm is a VirtualMuxAlarm, we must register as a client of the
        // MuxAlarm in order to guarantee that requested interrupts are not
        // dropped.
```
that we could clean up since the VirtualAlarm would work whether or not the `set_alarm_client` was called. We are basically relying on the `set_alarm_client` function to register with the top-level `MuxAlarm`. Instead we should register the VirtualAlarm with the Mux when we create the VirtualAlarm.

I want to get feedback on this approach before change code since this would require a larger refactor. If you want me to upload a subset of this change to get a better feel of what the larger change would look like, let me know.

**Comment by hudson-ayers** [comment]
> We should stop leaking these implementation details on this hil.

+1. The HIL should not expose details that only apply if the device is virtualized.

> Once way to fix (i.e. drop the 'a on the hil interfaces) is to require that after a VirtualMuxAlarm has been created (which takes in a refernce to MuxAlarm) we call a new link(virtual_alarm: &'a VirtualAlarmMux) on MuxAlarm after creating the VirtualMuxAlarm::new(). This requires a two step initialization for VirtualAlarmMux and could be prone to mistakes, but it alleviates the lifetime issue. 

If I am not missing something, this seems largely equivalent to how `VirtualSpiMasterDevice` handles this, which I agree seems like the correct approach. In the case of SPI, the function you call `link` is called `setup`, and rather than being a method on the `Mux` it is a method on the `VirtualX`, because the `VirtualX` has a reference to the mux. There is some small overhead to every virtual device holding a reference to the mux, but for the sake of being uniform it would be nice to have spi and alarm handle this the same way. 

> Could we perhaps use the Component and finalize paradigm to ensure that VirtualMuxAlarms are always created correctly, i.e VirtualAlarmMux::new then MuxAlarm::link?

Yes, that is the right approach. This should be easy for the common case of setting up the alarm driver, as there is already a component for that. We should probably also add a component just for creating a virtual alarm which could then take care of the 2-step initialization. 

> Also there is a comment on VirtualSchedulerTimer:

Yep, that bugged me when I wrote this comment, would be nice to be able to get rid of it :)

> I want to get feedback on this approach before change code since this would require a larger refactor. If you want me to upload a subset of this change to get a better feel of what the larger change would look like, let me know.

Looks good to me, @phil-levis do you have any thoughts as the resident time HIL expert?
