### ISSUE TITLE
QEMU RISC-V 32-bit board cannot run userspace applications (upstream QEMU PMP bug)

### ISSUE THREAD

**Issue by CarlosRFS** [tock/tock#3316]
I'm having some troubles trying to run tockOS together with an application on Qemu
when i clone with --recursive libtock-rs and run 
make qemu-example EXAMPLE=low_level_debug 
qemu launches and the example run

but if a try run 
make run-app APP=low_level_debug.tbf 
on tock/boards/qemu-rv32_virt/

qemu-system-riscv32 \
  -machine virt \
  -bios /home/haver/HD/trabalho/libtock-rs/tock/target/riscv32imac-unknown-none-elf/release/qemu_rv32_virt.elf \
  -global virtio-mmio.force-legacy=false \
  -device virtio-rng-device \
  -device loader,file=low_level_debug.tbf,addr=0x20040048 \
  -nographic
QEMU RISC-V 32-bit "virt" machine, initialization complete.
Entering main loop.

tockOS boots but the example doesnt run(when reproducing this you can close qemu with 'pkill qemu')
OBS:this tbf i tested was generated by the libtock-rs make command above in 
libtock-rs/target/riscv32imac-unknown-none-elf/release/examples/exercicio.tbf

  
the makefile in tock/boards/qemu-riscv32/ has some problem? 
in the link below the instruction are to use make run-app to run a aplication
https://github.com/tock/tock/blob/master/boards/qemu_rv32_virt/README.md 

and someone can tell me if theres a way of running 2 apps simultaneously on tockOS running on qemu?

**Comment by lschuermann** [comment]
I’m sorry you have run into this, this is actually a known issue which I am trying to resolve in upstream QEMU currently. This is in fact not a Tock, but a QEMU bug you’re running into. If you happen to build QEMU from source, you should be able to make it work with the following patch:

    https://lists.gnu.org/archive/html/qemu-devel/2022-09/msg01445.html

I’m going to add this to the board’s documentation, as well as how to run two applications simultaneously on the board. In the meantime, you can use the `hifive1` board on QEMU, that should work just fine.

Also, I’d use this issue as a tracker for any new developments on getting user space applications to work on the QEMU RISC-V 32-bit virtual board running on mainline QEMU.

**Comment by CarlosRFS** [comment]
i was thinking the qemu-rv32-virt was an hifive1 kernel too like in the makefile of libtock-rs, but fine, thanks for the answer, can you tell me if using the hifive1 on qemu make possible to loader an aplication by tockloader?

**Comment by lschuermann** [comment]
> i was thinking the qemu-rv32-virt was an hifive1 kernel too like in the makefile of libtock-rs

Technically speaking, the Tock board definitions of the `hifive1` and `qemu_riscv32_virt` are very similar, and they even share some of the `sifive` peripherals. However, this seems to be largely caused by the nature of how the QEMU support for RISC-V was initially developed. I would expect those targets to diverge more significantly in the future. Binaries produced for both targets are not compatible, though. So while both run in QEMU, be sure to set the QEMU machine model to the one you compiled Tock for (as indicated in the respective board READMEs).

> can you tell me if using the hifive1 on qemu make possible to loader an aplication by tockloader?

Sure, this is further outlined in the board's README. In essence, you run the following command in the boards' root (assuming you've already compiled the `c_hello` app in `libtock-c`):

```
tock/boards/hifive1 $ make qemu-app \
    APP=$YOUR_LIBTOCK_C_REPO/examples/c_hello/build/rv32imac/rv32imac.0x20040060.0x80002800.tbf
```

Loading multiple applications will be significantly easier for the `qemu_rv32_virt` board. It turns out that the QEMU issues have been fixed upstream, so we're currently waiting for a new release which will fix application support in Tock. Alternatively you can compile QEMU from source and use that.

**Comment by CarlosRFS** [comment]
> Sure, this is further outlined in the board's README. In essence, you run the following command in the boards' root (assuming you've already compiled the `c_hello` app in `libtock-c`):
> 
> ```
> tock/boards/hifive1 $ make qemu-app \
>     APP=$YOUR_LIBTOCK_C_REPO/examples/c_hello/build/rv32imac/rv32imac.0x20040060.0x80002800.tbf
> ```
> 
> Loading multiple applications will be significantly easier for the `qemu_rv32_virt` board. It turns out that the QEMU issues have been fixed upstream, so we're currently waiting for a new release which will fix application support in Tock. Alternatively you can compile QEMU from source and use that.

Thanks
