### ISSUE TITLE
Wishlist: Explore error-on-format-failed

### ISSUE THREAD

**Issue by ppannuto** [tock/tock#3477]
Just [learned about this option](https://github.com/rust-lang/rustfmt/issues/4119#issuecomment-1401001368), `error_on_unformatted = true` for rustfmt. Might save folks from unexpected stuff like in #3475. Without having tested it at all, I am assuming there's a bunch of other minor things that would trip on this, so will take a procrastination-oriented afternoon someday :)

**Comment by hudson-ayers** [comment]
Oh this seems great. I took a look at fixing this and currently there are 87 pieces of code in the repo that cannot be formatted correctly because of comment location. I think we should move all of those comments to places that do not break rustfmt and then add a `.rustfmt.toml` to the repo that only enables this option.

**Comment by bradjc** [comment]
#3512

**Comment by hudson-ayers** [comment]
Fixed by #3512

**Comment by ppannuto** [comment]
Closed via #3512
